VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = no

UNICODE_ENABLE = yes
OS_DETECTION_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes

VELOCIKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
VIALRGB_ENABLE = no
RGBLIGHT_DRIVER = ws2812
WS2812_DRIVER = vendor

SRC += features/achordion.c
